require 'roark/aws/ec2/ami_state'
require 'roark/aws/ec2/ami_tags'
require 'roark/aws/ec2/ami_authorizations'
require 'roark/aws/ec2/create_ami'
require 'roark/aws/ec2/destroy_ami'
require 'roark/aws/ec2/instance_status'
require 'roark/aws/ec2/stop_instance'
